/* Generated by bin2c, do not edit manually */
#ifndef __song1_h_included
#define __song1_h_included

/* Contents of file song1.raw */
extern const long int song1_raw_size;
extern const unsigned char song1_raw[360048];

#endif    /* __song1_h_included */
